## This is basic continuous integration build for your Quarkus application.

name: Release

on:
  push:
    branches: [ main ]

jobs:
  hugo:
    runs-on: [ podman ]
    steps:
    - uses: actions/checkout@master
      with:
        submodules: 'true'
    - uses: jakejarvis/hugo-build-action@master  # ...or replace 'master' with a full version tag, such as: v0.64.1
      with:
        args: --minify
    - uses: actions/upload-artifact@master
      with:
        name: website
        path: './public'
    - name: Upload Artifact
      id: upload-website
      uses: actions/upload-artifact@v2
      with:
        name: kaiserpfalz-edv
        path: public
        retention-days: 1


  container-build:
    runs-on: [ podman ]
    needs: hugo
    steps:
    - name: checkout sources
      id: checkout-sources
      uses: actions/checkout@v2

    - name: retrieve build
      id: retrieve-build
      uses: actions/download-artifact@v2
      with:
        name: kaiserpfalz-edv

    - name: Buildah
      id: build-container
      uses: redhat-actions/buildah-build@v2
      with:
        image: static-kaiserpfalz-edv
        tags: release
        dockerfiles: ./Dockerfile
        context: ./

    - name: Push To quay
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: static-kaiserpfalz-edv
        tags: release
        registry: ${{ secrets.QUAY_REPO }}
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_TOKEN }}
